config/routes.rb
BarkleyAdoption::Application.routes.draw do

  resources :resources

  resources :timelines

  resources :comments

  devise_for :users

  mount Ckeditor::Engine => '/ckeditor'

  resources :posts do
    resources :comment2s, :only => [:create]
  end

  get "pages/home"

  get "pages/about"

  get "pages/donate"

  get "pages/timeline"

  get "pages/resources"

  root :to => 'pages#home'

  match '/resources', :to => 'pages#resources'
  match '/timeline', :to => 'pages#timeline'

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :r_content, "resource description" %><br />
    <%= f.cktext_area :r_content, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} } %>
  </div>
  <div class="field">
    <%= f.label :amazon, "Amazon Link" %><br />
    <%= f.cktext_area :amazon, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} } %>
  </div>
  <div class="field">
    <%= f.label :desc, "Another Random Field" %><br />
    <%= f.cktext_area :desc, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>s

app/views/resources/edit.html.erb
<h1>Editing resource</h1>
<% if user_signed_in? %>
	<% if current_user.has_role? :admin %>
<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>
<% end %>
<% end %>

app/views/resources/index.html.erb
<h1>Adoption Resources</h1>
<br />


<% @resources.each do |resource| %>

    <%=h resource.r_content.html_safe %>
    <%=h resource.amazon.html_safe %>
    <%=h resource.desc.html_safe %>

          <% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
    <%= link_to 'Show', resource %>

    <%= link_to 'Edit', edit_resource_path(resource) %>
    <%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <% end %>

<% end %>

<br />
<% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
<%= link_to 'New Resource', new_resource_path %>
<% end %>
<% end %>

app/views/resources/new.html.erb
<h1>New resource</h1>
<% if user_signed_in? %>
	<% if current_user.has_role? :admin %>
<%= render 'form' %>
<% end %>
<% end %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>R content:</b>
  <%=h @resource.r_content.html_safe %>
</p>

<p>
  <b>Amazon:</b>
  <%=h @resource.amazon.html_safe %>
</p>

<p>
  <b>Desc:</b>
  <%=h @resource.desc.html_safe %>
</p>

<% if user_signed_in? %>
	<% if current_user.has_role? :admin %>
<%= link_to 'Edit', edit_resource_path(@resource) %> |
<% end %>
<% end %>
<%= link_to 'Back', resources_path %>