config/routes.rb
BarkleyAdoption::Application.routes.draw do

  resources :resources

  resources :timelines

  resources :comments

  devise_for :users

  mount Ckeditor::Engine => '/ckeditor'

  resources :posts do
    resources :comment2s, :only => [:create]
  end

  get "pages/home"

  get "pages/about"

  get "pages/donate"

  get "pages/timeline"

  get "pages/resources"

  root :to => 'pages#home'

  match '/resources', :to => 'pages#resources'
  match '/timeline', :to => 'pages#timeline'

end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
  attr_accessible :t_content
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  # GET /timelines
  # GET /timelines.json
  def index
    @timelines = Timeline.find(:all, :order => 'created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @timelines }
    end
  end

  # GET /timelines/1
  # GET /timelines/1.json
  def show
    @timeline = Timeline.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @timeline }
    end
  end

  # GET /timelines/new
  # GET /timelines/new.json
  def new
    @timeline = Timeline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @timeline }
    end
  end

  # GET /timelines/1/edit
  def edit
    @timeline = Timeline.find(params[:id])
  end

  # POST /timelines
  # POST /timelines.json
  def create
    @timeline = Timeline.new(params[:timeline])

    respond_to do |format|
      if @timeline.save
        format.html { redirect_to @timeline, notice: 'Timeline was successfully created.' }
        format.json { render json: @timeline, status: :created, location: @timeline }
      else
        format.html { render action: "new" }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /timelines/1
  # PUT /timelines/1.json
  def update
    @timeline = Timeline.find(params[:id])

    respond_to do |format|
      if @timeline.update_attributes(params[:timeline])
        format.html { redirect_to @timeline, notice: 'Timeline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @timeline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timelines/1
  # DELETE /timelines/1.json
  def destroy
    @timeline = Timeline.find(params[:id])
    @timeline.destroy

    respond_to do |format|
      format.html { redirect_to timelines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/views/timelines/_form.html.erb
<%= form_for(@timeline) do |f| %>
  <% if @timeline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timeline.errors.count, "error") %> prohibited this timeline from being saved:</h2>

      <ul>
      <% @timeline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :t_content, "Timeline Content" %><br />
    <%= f.cktext_area :t_content, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timelines/edit.html.erb
<h1>Editing timeline</h1>
<% if user_signed_in? %>
	<% if current_user.has_role? :admin %>
<%= render 'form' %>
<% end %>
<% end %>

<%= link_to 'Show', @timeline %> |
<%= link_to 'Back', timelines_path %>

app/views/timelines/index.html.erb
<h1>Timeline</h1>
<br />

<% @timelines.each do |timeline| %>
  <tr>
    <%=h timeline.t_content.html_safe %>

        <% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
    <td><%= link_to 'Show', timeline %></td>
    <td><%= link_to 'Edit', edit_timeline_path(timeline) %></td>
    <td><%= link_to 'Destroy', timeline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
    <% end %>

<% end %>


<br />
<% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
<%= link_to 'New Timeline', new_timeline_path %>
<% end %>
<% end %>

app/views/timelines/new.html.erb
<h1>New timeline</h1>
<% if user_signed_in? %>
	<% if current_user.has_role? :admin %>
<%= render 'form' %>
<% end %>
<% end %>

<%= link_to 'Back', timelines_path %>

app/views/timelines/show.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
	<% if current_user.has_role? :admin %>
<p>
  <b>content:</b>
  <%=h @timeline.t_content.html_safe %>
</p>

<% end %>
<% end %>
<%= link_to 'Edit', edit_timeline_path(@timeline) %> |
<%= link_to 'Back', timelines_path %>